name: Lint with black

on:
  push:
    paths:
      - 'src/**.py'
  pull_request:
    paths:
      - 'src/**.py'

jobs:
  lint:
    name: Run black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@24.8.0
